### ISSUE TITLE
TFRecords generation

### ISSUE THREAD

**Issue by crankyz** [dr-pato/audio_visual_speech_enhancement#1]
The last attribute is norm_data_dir, but where to get it?
--norm_data_dir <normalization_data_dir>

Got errors like that: FileNotFoundError: [Errno 2] No such file or directory: 'norm/bbal5n_with_s2_bbap7s.npy_video_mean.npy'

But I dont see where we make that kind of files before.

**Comment by dr-pato** [comment]
Hi. The attribute is the directory where the script will save normalization data (e.g. audio and video mean and standard deviation for each speaker). You can save the data wherever you want.

It seems that something went wrong because the format of normalization file should be "<norm_data_dir>/s<speaker_id>_video_mean.npy". If your dataset does not have the structure described in "Usage" section the code will not work.

**Comment by crankyz** [comment]
Yeap, probably there some problem with directory structures. If you have time, could you provide directory structure for TFRecords generation, please? I have that structure :
/data_dir
   /s1
        /audio
            /npy and wavs
        /TBM
            /npy
        /video
            /mpg and txt

    /mix
           /TRAINING_SET
               /files like bbaf2s_with_s2_bbaj5a.npy
           /VALIDATION_SET
           /TEST_SET

And run that code:
python av_speech_enhancement.py tfrecords_generator --data_dir data_dir --num_speakers 2 --mode fixed --dest_dir tfrecords --base_audio_dir audio --video_dir video --tbm_dir TBM --mix_audio_dir mix --delta 1 --norm_data_dir norm

And got that:
Creating training TFRecords...
Computing mean and std of video features of speaker s1...
Total number of files = 0

Thank you anyway for your help.

**Comment by dr-pato** [comment]
Mixed-speech directory must have the following structure:
```
/mix
       /TRAINING_SET
            /s1
                 /bbaf2s_with_s2_bbaj5a.wav
                 /bbaf2s_with_s2_bbaj5a.npy
                 ...
       /VALIDATION_SET
             ...
       /TEST_SET
             ...
```
Both wavs and npy must be present.

Moreover, in your case it looks like that the script does not find any video features file (in "video" subdirectory with ".txt" extension).

**Comment by crankyz** [comment]
Also Tryed to copy video_txt_files in data_dir/s1/video
also in mix/TRAINING_SET/s1/video/ 
but no luck also Total number of files = 0

**Comment by dr-pato** [comment]
Video files must be in the directory data_dir/s1/video while mixed-speech files must be in the directory data_dir/mix/TRAINING_SET/s1.

Look at the function "get_filenames_2spk" (line 177 in create_dataset_tfrecords.py) to check the correct location of files you need to generate tfrecords.

**Comment by crankyz** [comment]
Thank you, finally I found the solution with your help,-- removed  'data_path' in mix_audio_file_list = glob(os.path.join(data_path, mix_audio_folder, '*.wav')) 
so the new line now - "mix_audio_file_list = glob(os.path.join(mix_audio_folder, '*.wav')) " , and looks like it works. Thank you again Giovanni.
