### ISSUE TITLE
mean and standard deviation file

### ISSUE THREAD

**Issue by pradnyapagar05** [dr-pato/audio_visual_speech_enhancement#14]
Hello sir,
Thank you for helping me in previous issue.

What should be location of norm_data_dir create while running create_dataset_tfrecord.py file.Is num_data_dir need to be store somewhere for future processing ???

**Comment by dr-pato** [comment]
Hi,
you can store norm_data_dir where you want, the location is not important. You need normalization files when you generate tfrecords ('tfrecords_generator' subcommand). Check the usage with '-h' option.
