### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by truewangxiaolong** [dr-pato/audio_visual_speech_enhancement#20]
Could you please show me what kind of format should I put after "--base_speaker_ids" .For the speakers list like (s1 s2 s3 s4 s5...)
I have tried : 
--base_speaker_ids s1 s2 s3 s4 
--base_speaker_ids s1+s2+ s3+s4
--base_speaker_ids s1&s2&s3&s4
--base_speaker_ids (s1 s2 s3 s3 s4)
--base_speaker_ids s1,s2,s3,s4
But it doesn't work.
So what should I input?
Thank you so much.

**Comment by dr-pato** [comment]
Hi, you have to input just the speakers numbers like "1 2 3 4". You can read the command line help to understand the format of the parameters typing "av_speech_enhancement.py <subcommand> -h".

Hope this helps.
Best,
Giovanni

**Comment by truewangxiaolong** [comment]
yeah, I have changed the "base_speaker_ids" from "s1 s2"to "1 2" when I saw the "type=int" in  the av_speech_enhancement.py  before .
And it's do work. Thank you so much.
