### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by truewangxiaolong** [dr-pato/audio_visual_speech_enhancement#24]
Hi @dr-pato 
There are some questions when I'm training the model.
Could you please show me what parameter would be suitable in the training :
--hidden_units','Number of units of BLSTM cells
and
'--layers', 'Number of stacked BLSTM cells'
for the model 'vl2m' or 'av_concat_mask_ref'.
Thank you so much.
Best,
Yuyue.

**Comment by dr-pato** [comment]
Hy @truewangxiaolong,
you can find all the information about the parameters in the paper https://arxiv.org/pdf/1811.02480.pdf
The number of hidden units is set to 250 for all models. The number of layers is 5 and 3 for 'vl2m' and 'av_concat_mask_ref', respectively.

Best,
Giovanni

**Comment by truewangxiaolong** [comment]
Hi @dr-pato 
Oh ,I see.
It's so kind of you for reply me.
Thank you so much.
Best,
Yuyue.
