### ISSUE TITLE
Can't Understand the directory structure

### ISSUE THREAD

**Issue by Priyanka-narode** [dr-pato/audio_visual_speech_enhancement#5]
I am very new to Neural Network and python programming in general. 
I cloned the repository and created the audio and video files. 
I am not understanding how to run and substitute the parameters for the following command
`av_speech_enhancement.py mixed_speech_generator
	--data_dir <data_dir>
	--base_speaker_ids <spk1> <spk2> <...>
	[--noisy_speaker_ids <spk1> <spk2> <...>]
	--audio_dir <audio_dir>
	--dest_dir <dest_dir>
	--num_samples <num_samples>
	--num_mix <num_mix>
	--num_mix_speakers <num_mix_speakers> {1,2}`

I tried the following way with no luck
` python3 av_speech_enhancement.py mixed_speech_generator --data_dir data --base_speaker_ids S1 S2 S3 S4 --audio_dir data/S1/audio --dest_dir dest --num_samples 4 --num_mix 4 --num_mix_speakers 4 {1,2}`

Please try to help me and give me some hints to solve the issue.

Thanks in advance

**Comment by dr-pato** [comment]
Hi Priyanka-narode,
You can try with the following command:
`python3 av_speech_enhancement.py mixed_speech_generator --data_dir data --base_speaker_ids 1 2 3 4 --audio_dir audio --dest_dir dest --num_samples 4 --num_mix 4 --num_mix_speakers 1`

I suggest you to check the correct syntax using the command line documentation. In this case must type:
`python3 av_speech_enhancement.py mixed_speech_generator --help`

Remember that folders must be organized as described in the README.

Let me know if you will be able to make things work.

Best,
Giovanni
