### ISSUE TITLE
Training function arguments  problem

### ISSUE THREAD

**Issue by malineha** [dr-pato/audio_visual_speech_enhancement#7]
hello sir,
I am executing this code in google colab.
I  refer following functions and parameters: 
  
config = Configuration(args.learning_rate, args.updating_step, args.learning_decay, args.dropout, args.batch_size,args.opt, args.video_dim, args.audio_dim, args.num_audio_samples, args.epochs, args.hidden_units,args.layers, args.regularization, args.mask_threshold)

  train(args.model, args.data_dir, args.train_set, args.val_set, config, args.exp, args.mode)

I passed following args to these function

 config = Configuration(0.5, 10000, 1.0, 1, 1,'adam',136, 257, 100, 60, 250,5, 0, -1)
train('vl2m', '/content/drive/My Drive/data_dir', 'tfr/TRAINING_SET', 'tfr/VALIDATION_SET', 'config',' 0', 'fixed') 

****problem****
->train_dataset, train_it = train_data_manager.get_iterator(train_dataset, batch_size=config.batch_size, n_epochs=config.num_epochs, train=True)

AttributeError: 'str' object has no attribute 'batch_size'  

also...I faced same errors in DataManager function for 
contrib.audio_dim,contrib.video_dim and for num_audio_samples

Plz help me to solve this issue

**Comment by dr-pato** [comment]
Hi malineha,
I think the problem is in 'train' arguments. You are passing tre string 'config' but actually you have to pass the config object without brackets. Indeed, a string don't have attribute 'batch size'...
Hope this helps to make the code running.

Best,
Giovanni

**Comment by malineha** [comment]
Thank you..!

sir can u plz help me for passing following arguments value .....if I have 1000 records for per speaker(1000 audio and 1000 video)...in which this model working on 2 speakers


config = Configuration(args.learning_rate, args.updating_step, args.learning_decay, args.dropout, args.batch_size,args.opt, args.video_dim, args.audio_dim, args.num_audio_samples, args.epochs, args.hidden_units,args.layers, args.regularization, args.mask_threshold)

train(args.model, args.data_dir, args.train_set, args.val_set, config, args.exp, args.mode)

Can u plz give me a example for 1000 records.Because batch size error is generating...I didnt understand what it should be...

**Comment by dr-pato** [comment]
Hi,
please send me the error log message so I can check it.

Giovanni

**Comment by malineha** [comment]
Sorry Sir...actually I am very new to Neural Network and python programming in general.
I figured out all that mistakes I did from start...
I need to change my dataset..
I am executing this code in google colab...and because of google drive limit of 15gb I am using 10 speakers data...
Sir...is it ok to implement this model using 10 speakers dataset...in which I split data in 6/2/2

**Comment by dr-pato** [comment]
You can do it but keep in mind that in general you need more speakers in training set to reach good generalization on unseen speakers.
