### ISSUE TITLE
Training has "None values not supported"

### ISSUE THREAD

**Issue by nanometer34688** [dr-pato/audio_visual_speech_enhancement#9]
I have tried using Tensorflow-gpu versions 1.15.0 and converted your training script to use Tensorflow-gpu 2.10.0. 

My data structure is as follows:

 ```
/data
        /TRAINING_SET
            /s2_l_bgwj2n_with_s4_s4_l_pwiv4a.npy
            /s2_l_bgwj2n_with_s4_s4_l_pwiv4a.wav
            ...
        /VALIDATION_SET
        ...
        /TEST_SET
       ...
```

 

My TFrecords get produced as expected:

```
/tf_records
       /TRAINING_SET
           /sample_00000.tfrecords
           /sample_00002.tfrecords
           ...
       /VALIDATION_SET
       ...
       /TEST_SET
      ...
```

But when it comes to training using the VL2m, "None values are not supported"
Have you come across this before?

**Comment by dr-pato** [comment]
Hi,
Can you give me more information about the error? Maybe the error log will be useful..

Giovanni

**Comment by nanometer34688** [comment]
Apologies. This was my mistake. 

I realised I was not correctly pointing to the TF records I had previously created.
